<?php

declare(strict_types=1);

namespace SysRevAI\Services;

use SysRevAI\Models\ArticleCriticalReport;
use SysRevAI\Models\CopilotMessage;

/**
 * Renders an article's critical report (and, optionally, the full
 * Copilot chat transcript) as DOCX via PhpWord or PDF via Dompdf.
 *
 * Two scopes are supported, controlled by the user from the workspace:
 *   - 'report'      → just the critical report sections.
 *   - 'report_chat' → critical report + chat transcript appended.
 *
 * Both writers consume the same internal struct produced by
 * {@see self::collect()} and emit the same sections — score table,
 * executive summary, strengths / weaknesses, methodology critique,
 * statistical / ethical / reproducibility concerns, literature
 * positioning, publication outlook, devil's advocate and
 * section-by-section recommendations — so the two output formats stay
 * in sync with the web view.
 */
final class ArticleExportService
{
    public const SCOPE_REPORT      = 'report';
    public const SCOPE_REPORT_CHAT = 'report_chat';

    /** Tone palette used by both writers so the colour vocabulary matches. */
    private const COLOUR_TEXT      = '1F2937';
    private const COLOUR_MUTED     = '4B5563';
    private const COLOUR_BORDER    = 'E5E7EB';
    private const COLOUR_BG_LIGHT  = 'F3F4F6';
    private const COLOUR_BG_DEVIL  = 'FFFBEB';
    private const COLOUR_BG_GOOD   = 'ECFDF5';
    private const COLOUR_BG_BAD    = 'FEF2F2';
    private const COLOUR_ACCENT    = '4F46E5';
    private const COLOUR_OK        = '0A7D4D';
    private const COLOUR_WARN      = 'A16207';
    private const COLOUR_FAIL      = 'B91C1C';
    private const COLOUR_DEVIL     = 'D97706';

    /** @return list<string> */
    public static function scopes(): array
    {
        return [self::SCOPE_REPORT, self::SCOPE_REPORT_CHAT];
    }

    /**
     * Build the language-agnostic export payload: the report axes / prose
     * blocks, optional chat transcript and the article header. Callers
     * pass the article row + the resolved current user id; the service
     * pulls the cached report and the chat history itself.
     *
     * @param array<string,mixed> $article
     * @return array{
     *   article: array<string,mixed>,
     *   report: ?array<string,mixed>,
     *   reportRow: ?array<string,mixed>,
     *   chat: list<array{role:string,content:string,created_at:string}>,
     *   include_chat: bool
     * }
     */
    private static function collect(array $article, int $userId, string $scope): array
    {
        $aid = (int) ($article['id'] ?? 0);
        $row = ArticleCriticalReport::find($aid);
        $report = $row !== null ? ArticleCriticalReport::decode($row) : null;

        $includeChat = $scope === self::SCOPE_REPORT_CHAT;
        $chat = [];
        if ($includeChat) {
            foreach (CopilotMessage::history(null, $userId, 500, $aid) as $m) {
                $chat[] = [
                    'role'       => (string) ($m['role'] ?? ''),
                    'content'    => (string) ($m['content'] ?? ''),
                    'created_at' => (string) ($m['created_at'] ?? ''),
                ];
            }
        }

        return [
            'article'      => $article,
            'report'       => $report,
            'reportRow'    => $row,
            'chat'         => $chat,
            'include_chat' => $includeChat,
        ];
    }

    /* ── DOCX ──────────────────────────────────────────────────────────── */

    /**
     * @param array<string,mixed> $article
     * @return array{bytes:?string,error:?string}
     *
     * The .docx is generated by the hand-rolled {@see ArticleDocxBuilder}
     * rather than PhpWord. The bundled PhpWord 1.x ships several
     * ordering bugs in its OOXML output (table writer emits tblGrid
     * before tblPr; styles.xml writes <w:style> children in insertion
     * order; pPr / rPr children are also out of schema order). Word
     * rejected the result no matter how much we patched the bytes
     * after the fact, so the builder emits canonical OOXML directly.
     */
    public static function docx(array $article, int $userId, string $scope): array
    {
        $data = self::collect($article, $userId, $scope);
        if ($data['report'] === null) {
            return ['bytes' => null, 'error' => 'no_report'];
        }
        $bytes = ArticleDocxBuilder::build($data);
        if ($bytes === '') {
            return ['bytes' => null, 'error' => 'docx_build_failed'];
        }
        return ['bytes' => $bytes, 'error' => null];
    }

    /* ── PDF ───────────────────────────────────────────────────────────── */

    /**
     * @param array<string,mixed> $article
     * @return array{bytes:?string,error:?string}
     */
    public static function pdf(array $article, int $userId, string $scope): array
    {
        if (!class_exists(\Dompdf\Dompdf::class)) {
            return ['bytes' => null, 'error' => 'dompdf_not_installed'];
        }
        $data = self::collect($article, $userId, $scope);
        if ($data['report'] === null) {
            return ['bytes' => null, 'error' => 'no_report'];
        }

        $html = self::renderHtml($data);

        $dompdf = new \Dompdf\Dompdf([
            'isRemoteEnabled'      => false,
            'isHtml5ParserEnabled' => true,
            'defaultFont'          => 'DejaVu Sans',
        ]);
        $dompdf->loadHtml($html, 'UTF-8');
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        return ['bytes' => $dompdf->output(), 'error' => null];
    }

    /**
     * @param array<string,mixed> $data
     */
    private static function renderHtml(array $data): string
    {
        $report  = (array) ($data['report'] ?? []);
        $article = (array) ($data['article'] ?? []);
        // Language the report was generated in — section headings resolve
        // through __in() so a French report keeps French headings even
        // when the exporting user's UI runs in Catalan. Empty ('' — reports
        // generated before the language selector) falls back to the UI locale.
        $lang = (string) ($report['language'] ?? '');
        $esc = static fn (string $s): string => htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $prose = static function (string $text) use ($esc): string {
            $out = '';
            foreach (preg_split('/\n{2,}/', trim($text)) ?: [$text] as $chunk) {
                $chunk = trim((string) $chunk);
                if ($chunk !== '') {
                    $out .= '<p>' . nl2br($esc($chunk)) . '</p>';
                }
            }
            return $out;
        };

        $title = (string) ($article['title'] ?: '—');
        $generatedAt = '';
        if (($data['reportRow'] ?? null) !== null && !empty($data['reportRow']['updated_at'])) {
            $generatedAt = (string) __in($lang, 'articles.critical.generated_at', (string) $data['reportRow']['updated_at']);
        }
        $overall = (string) ($report['overall'] ?? '');

        $axesHtml = '<table class="scores"><tbody>';
        foreach (ArticleCriticalReport::AXES as $axis) {
            $score = max(0, min(100, (int) ($report[$axis] ?? 0)));
            $note  = (string) ($report[$axis . '_note'] ?? '');
            $label = (string) __in($lang, 'articles.critical.axis_' . $axis);
            $tone  = $score >= 80 ? '#0a7d4d' : ($score >= 50 ? '#a16207' : '#b91c1c');
            $axesHtml .= '<tr class="score-row">'
                . '<td class="score-label">' . $esc($label) . '</td>'
                . '<td class="score-bar-cell">'
                . '<div class="bar"><span style="width:' . $score . '%; background:' . $tone . '"></span></div>'
                . '</td>'
                . '<td class="score-num" style="color:' . $tone . '">' . $score . ' / 100</td>'
                . '</tr>';
            if ($note !== '') {
                $axesHtml .= '<tr class="score-note-row"><td colspan="3" class="score-note">' . nl2br($esc($note)) . '</td></tr>';
            }
        }
        $axesHtml .= '</tbody></table>';

        $strengths  = (array) ($report['key_strengths']  ?? []);
        $weaknesses = (array) ($report['key_weaknesses'] ?? []);
        $swHtml = '';
        if ($strengths !== [] || $weaknesses !== []) {
            $bullets = static function (array $items) use ($esc): string {
                $out = '<ul>';
                foreach ($items as $it) {
                    $s = trim((string) $it);
                    if ($s !== '') {
                        $out .= '<li>' . $esc($s) . '</li>';
                    }
                }
                return $out . '</ul>';
            };
            $swHtml .= '<h2>' . $esc((string) __in($lang, 'articles.critical.h_key_strengths')) . ' / '
                . $esc((string) __in($lang, 'articles.critical.h_key_weaknesses')) . '</h2>'
                . '<table class="sw"><tr>';
            if ($strengths !== []) {
                $swHtml .= '<td class="sw-col sw-good">'
                    . '<div class="sw-title">' . $esc((string) __in($lang, 'articles.critical.h_key_strengths')) . '</div>'
                    . $bullets($strengths) . '</td>';
            }
            if ($weaknesses !== []) {
                $swHtml .= '<td class="sw-col sw-bad">'
                    . '<div class="sw-title">' . $esc((string) __in($lang, 'articles.critical.h_key_weaknesses')) . '</div>'
                    . $bullets($weaknesses) . '</td>';
            }
            $swHtml .= '</tr></table>';
        }

        $concernsHtml = '';
        foreach ([
            ['h_statistical_concerns',  (array) ($report['statistical_concerns']  ?? [])],
            ['h_ethical_concerns',      (array) ($report['ethical_concerns']      ?? [])],
            ['h_reproducibility',       (array) ($report['reproducibility_notes'] ?? [])],
        ] as [$key, $items]) {
            if ($items === []) {
                continue;
            }
            $concernsHtml .= '<h2>' . $esc((string) __in($lang, 'articles.critical.' . $key)) . '</h2><ul>';
            foreach ($items as $it) {
                $s = trim((string) $it);
                if ($s !== '') {
                    $concernsHtml .= '<li>' . $esc($s) . '</li>';
                }
            }
            $concernsHtml .= '</ul>';
        }

        $recsHtml = '';
        $recs = (array) ($report['recommendations'] ?? []);
        if ($recs !== []) {
            $recsHtml .= '<h2>' . $esc((string) __in($lang, 'articles.critical.h_recommendations')) . '</h2>';
            foreach ($recs as $rec) {
                $sec = trim((string) ($rec['section'] ?? ''));
                if ($sec !== '') {
                    $recsHtml .= '<h3>' . $esc($sec) . '</h3>';
                }
                $items = (array) ($rec['items'] ?? []);
                if ($items !== []) {
                    $recsHtml .= '<table class="recs">';
                    foreach ($items as $it) {
                        if (is_array($it)) {
                            $text     = trim((string) ($it['text'] ?? ''));
                            $priority = (string) ($it['priority'] ?? 'medium');
                        } else {
                            $text     = trim((string) $it);
                            $priority = 'medium';
                        }
                        if ($text === '') {
                            continue;
                        }
                        $recsHtml .= '<tr>'
                            . '<td class="prio prio-' . $esc($priority) . '">'
                            . $esc((string) __in($lang, 'articles.critical.priority_' . $priority))
                            . '</td>'
                            . '<td class="rec-text">' . $esc($text) . '</td>'
                            . '</tr>';
                    }
                    $recsHtml .= '</table>';
                }
            }
        }

        $chatHtml = '';
        if ($data['include_chat'] && $data['chat'] !== []) {
            $chatHtml .= '<div class="page-break"></div>'
                . '<h2>' . $esc((string) __in($lang, 'articles.export.h_chat')) . '</h2>'
                . '<p class="muted">' . $esc((string) __in($lang, 'articles.export.chat_subtitle')) . '</p>';
            foreach ($data['chat'] as $m) {
                $who = $m['role'] === 'assistant'
                    ? (string) __in($lang, 'articles.export.who_assistant')
                    : (string) __in($lang, 'articles.export.who_user');
                $cls = $m['role'] === 'assistant' ? 'msg msg-assistant' : 'msg msg-user';
                $stamp = $m['created_at'] !== '' ? ' · ' . $m['created_at'] : '';
                $chatHtml .= '<div class="' . $cls . '">'
                    . '<div class="msg-head">' . $esc($who . $stamp) . '</div>'
                    . '<div class="msg-body">' . $prose($m['content']) . '</div>'
                    . '</div>';
            }
        }

        return '<!doctype html><html><head><meta charset="utf-8"><style>'
            . 'body { font-family: DejaVu Sans, sans-serif; color:#1f2937; font-size:11.5px; line-height:1.55; }'
            . 'h1 { font-size:22px; margin:0 0 4px; }'
            . '.subtitle { font-style:italic; color:#6b7280; margin:0 0 4px; font-size:11px; }'
            . '.meta { color:#6b7280; font-size:10px; margin:0 0 16px; }'
            . 'h2 { font-size:14px; margin:18px 0 6px; border-bottom:1px solid #e5e7eb; padding-bottom:4px; color:#1f2937; }'
            . 'h2.devil { border-left:3px solid #d97706; padding:4px 0 4px 8px; border-bottom:none; }'
            . 'h3 { font-size:12px; margin:14px 0 4px; color:#374151; text-transform:uppercase; letter-spacing:.04em; }'
            . 'p { margin:0 0 8px; }'
            . 'ul { margin:0 0 8px; padding-left:18px; }'
            . 'ul li + li { margin-top:4px; }'
            . '.muted { color:#6b7280; font-size:10.5px; }'
            . '.overall { font-weight:bold; background:#f3f4f6; padding:10px 12px; border-left:3px solid #4f46e5; margin:0 0 14px; font-size:12.5px; }'
            . '.devil-callout { background:#fffbeb; padding:10px 12px; border-left:3px solid #d97706; margin:0 0 14px; }'
            . '.devil-callout p:last-child { margin:0; }'
            /* Scores table — three columns: label / bar / score. */
            . '.scores { width:100%; border-collapse:collapse; margin:0 0 8px; }'
            . '.scores tr.score-row td { border-top:1px solid #e5e7eb; padding:8px 6px; vertical-align:middle; }'
            . '.scores tr:first-child td { border-top:0; }'
            . '.score-label { width:30%; font-weight:bold; font-size:12px; }'
            . '.score-bar-cell { width:52%; }'
            . '.bar { background:#e5e7eb; height:8px; border-radius:4px; overflow:hidden; }'
            . '.bar span { display:block; height:8px; }'
            . '.score-num { width:18%; text-align:right; font-weight:bold; font-size:11.5px; }'
            . '.score-note { padding:0 6px 10px; color:#4b5563; font-size:10.5px; line-height:1.45; border-top:0; }'
            /* Strengths / weaknesses side-by-side cards. */
            . '.sw { width:100%; border-collapse:separate; border-spacing:8px 0; }'
            . '.sw-col { vertical-align:top; padding:10px 12px; border-radius:6px; }'
            . '.sw-good { background:#ecfdf5; border-top:3px solid #0a7d4d; }'
            . '.sw-bad  { background:#fef2f2; border-top:3px solid #b91c1c; }'
            . '.sw-title { text-transform:uppercase; letter-spacing:.04em; font-weight:bold; font-size:10.5px; color:#4b5563; margin:0 0 6px; }'
            /* Recommendations table — priority badge + body. */
            . '.recs { width:100%; border-collapse:separate; border-spacing:0 4px; margin:6px 0; }'
            . '.recs td { vertical-align:top; padding:6px 8px; }'
            . '.prio { width:62px; text-align:center; font-weight:bold; font-size:9px; text-transform:uppercase; letter-spacing:.06em; border-radius:999px; }'
            . '.prio-high   { background:#fee2e2; color:#b91c1c; }'
            . '.prio-medium { background:#fef3c7; color:#92400e; }'
            . '.prio-low    { background:#e0e7ff; color:#3730a3; }'
            . '.rec-text { font-size:11px; }'
            /* Chat appendix. */
            . '.msg { border:1px solid #e5e7eb; border-radius:6px; padding:8px 10px; margin:0 0 10px; }'
            . '.msg-assistant { background:#f8fafc; }'
            . '.msg-user { background:#eef2ff; }'
            . '.msg-head { font-size:10.5px; color:#4b5563; margin-bottom:4px; font-weight:bold; }'
            . '.page-break { page-break-before:always; }'
            . '</style></head><body>'
            . '<h1>' . $esc($title) . '</h1>'
            . '<p class="subtitle">' . $esc((string) __in($lang, 'articles.export.doc_subtitle')) . '</p>'
            . ($generatedAt !== '' ? '<p class="meta">' . $esc($generatedAt) . '</p>' : '')
            . ($overall !== '' ? '<p class="overall">' . $esc($overall) . '</p>' : '')
            . '<h2>' . $esc((string) __in($lang, 'articles.export.h_scores')) . '</h2>'
            . $axesHtml
            . (!empty($report['summary']) ? '<h2>' . $esc((string) __in($lang, 'articles.critical.h_summary')) . '</h2>' . $prose((string) $report['summary']) : '')
            . $swHtml
            . (!empty($report['methodology_critique']) ? '<h2>' . $esc((string) __in($lang, 'articles.critical.h_methodology_critique')) . '</h2>' . $prose((string) $report['methodology_critique']) : '')
            . $concernsHtml
            . (!empty($report['literature_positioning']) ? '<h2>' . $esc((string) __in($lang, 'articles.critical.h_literature_positioning')) . '</h2>' . $prose((string) $report['literature_positioning']) : '')
            . (!empty($report['publication_outlook']) ? '<h2>' . $esc((string) __in($lang, 'articles.critical.h_publication_outlook')) . '</h2>' . $prose((string) $report['publication_outlook']) : '')
            . (!empty($report['devils_advocate']) ? '<h2 class="devil">' . $esc((string) __in($lang, 'articles.critical.h_devils_advocate')) . '</h2><div class="devil-callout">' . $prose((string) $report['devils_advocate']) . '</div>' : '')
            . $recsHtml
            . $chatHtml
            . '</body></html>';
    }
}
